In [2]:
from os import path
import pandas as pd
house = pd.read_csv('/content/drive/MyDrive/BostonHousing.csv')

In [3]:
house.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       501 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [6]:
house['rm'] = house['rm'].fillna(house['rm'].mean())

In [8]:
house.isna().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [9]:
y = house ['medv']
x = house.drop('medv', axis = 1)

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42)

In [39]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [40]:
y_pred=model.predict(x_test)

In [41]:
y_test

173    23.6
274    32.4
491    13.6
72     22.8
452    16.1
       ...
481    23.7
444    10.8
355    20.6
77     20.8
398     5.0
Name: medv, Length: 76, dtype: float64

In [42]:
from sklearn.metrics import mean_squared_error , mean_absolute_error , root_mean_squared_error , r2_score

In [43]:
mean_absolute_error (y_test,y_pred)

2.7679624961507754

In [45]:
root_mean_squared_error (y_test,y_pred)

3.7251495802166206

In [46]:
mean_squared_error (y_test,y_pred)

13.876739394988066

In [47]:
r2_score (y_test,y_pred)
#

0.7875049000000767