In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler, MinMaxScaler, Normalizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

import plotly.figure_factory as ff

In [22]:
df = pd.read_csv(r"D:\DEPI R4 ML\Data Sets\Sales.csv")

In [23]:
df.head()

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  object
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  object
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  object
 6   Customer_Gender   113036 non-null  object
 7   Country           113036 non-null  object
 8   State             113036 non-null  object
 9   Product_Category  113036 non-null  object
 10  Sub_Category      113036 non-null  object
 11  Product           113036 non-null  object
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), object(9)
memory usage: 15.5+ MB

In [25]:
df.describe()

,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
count,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000
mean,15.665753,2014.401739,35.919212,11.901660,267.296366,452.938427,285.051665,469.318695,754.370360
std,8.781567,1.272510,11.021936,9.561857,549.835483,922.071219,453.887443,884.866118,1309.094674
min,1.000000,2011.000000,17.000000,1.000000,1.000000,2.000000,-30.000000,1.000000,2.000000
25%,8.000000,2013.000000,28.000000,2.000000,2.000000,5.000000,29.000000,28.000000,63.000000
50%,16.000000,2014.000000,35.000000,10.000000,9.000000,24.000000,101.000000,108.000000,223.000000
75%,23.000000,2016.000000,43.000000,20.000000,42.000000,70.000000,358.000000,432.000000,800.000000
max,31.000000,2016.000000,87.000000,32.000000,2171.000000,3578.000000,15096.000000,42978.000000,58074.000000

In [7]:
df.isnull().sum()

Date                0
Day                 0
Month               0
Year                0
Customer_Age        0
Age_Group           0
Customer_Gender     0
Country             0
State               0
Product_Category    0
Sub_Category        0
Product             0
Order_Quantity      0
Unit_Cost           0
Unit_Price          0
Profit              0
Cost                0
Revenue             0
dtype: int64

In [26]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)
    
cat_cols = df.select_dtypes(include=["object"]).columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\omare\AppData\Local\Temp\ipykernel_13688\3038433415.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\omare\AppData\Local\Temp\ipykernel_13688\3038433415.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\omare\AppData\Local\Temp\ipykernel_13688\3038433415.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\omare\AppData\Local\Temp\ipykernel_13688\3038433415.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\omare\AppData\Local\Temp\ipykernel_13688\3038433415.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\omare\AppData\Local\Temp\ipykernel_13688\3038433415.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\omare\AppData\Local\Temp\ipykernel_13688\3038433415.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\omare\AppData\Local\Temp\ipykernel_13688\3038433415.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\omare\AppData\Local\Temp\ipykernel_13688\3038433415.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\omare\AppData\Local\Temp\ipykernel_13688\3038433415.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [10]:
df.drop_duplicates(inplace=True)

In [38]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [28]:
df_encoded = pd.get_dummies(df, drop_first=True)
df_encoded.head()

,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,Date_2011-01-02,...,"Product_Touring-3000 Blue, 62","Product_Touring-3000 Yellow, 44","Product_Touring-3000 Yellow, 50","Product_Touring-3000 Yellow, 54","Product_Touring-3000 Yellow, 58","Product_Touring-3000 Yellow, 62",Product_Water Bottle - 30 oz.,"Product_Women's Mountain Shorts, L","Product_Women's Mountain Shorts, M","Product_Women's Mountain Shorts, S"
0,26,2013,19,8,45,120,590,360,950,False,...,False,False,False,False,False,False,False,False,False,False
1,26,2015,19,8,45,120,590,360,950,False,...,False,False,False,False,False,False,False,False,False,False
2,23,2014,49,23,45,120,1366,1035,2401,False,...,False,False,False,False,False,False,False,False,False,False
3,23,2016,49,20,45,120,1188,900,2088,False,...,False,False,False,False,False,False,False,False,False,False
4,15,2014,47,4,45,120,238,180,418,False,...,False,False,False,False,False,False,False,False,False,False

In [29]:
scaler = StandardScaler()

num_cols_encoded = df_encoded.select_dtypes(include=["int64", "float64"]).columns
df_encoded[num_cols_encoded] = scaler.fit_transform(df_encoded[num_cols_encoded])

df_encoded.head()

,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,Date_2011-01-02,...,"Product_Touring-3000 Blue, 62","Product_Touring-3000 Yellow, 44","Product_Touring-3000 Yellow, 50","Product_Touring-3000 Yellow, 54","Product_Touring-3000 Yellow, 58","Product_Touring-3000 Yellow, 62",Product_Water Bottle - 30 oz.,"Product_Women's Mountain Shorts, L","Product_Women's Mountain Shorts, M","Product_Women's Mountain Shorts, S"
0,1.176817,-1.101559,-1.535056,-0.408046,-0.404298,-0.361078,0.671862,-0.123543,0.149440,False,...,False,False,False,False,False,False,False,False,False,False
1,1.176817,0.470144,-1.535056,-0.408046,-0.404298,-0.361078,0.671862,-0.123543,0.149440,False,...,False,False,False,False,False,False,False,False,False,False
2,0.835190,-0.315707,1.186801,1.160694,-0.404298,-0.361078,2.381544,0.639287,1.257844,False,...,False,False,False,False,False,False,False,False,False,False
3,0.835190,1.255996,1.186801,0.846946,-0.404298,-0.361078,1.989375,0.486721,1.018746,False,...,False,False,False,False,False,False,False,False,False,False
4,-0.075813,-0.315707,1.005344,-0.826377,-0.404298,-0.361078,-0.103664,-0.326965,-0.256950,False,...,False,False,False,False,False,False,False,False,False,False

In [30]:
scaler = MinMaxScaler()

df_encoded[num_cols_encoded] = scaler.fit_transform(df_encoded[num_cols_encoded])

In [31]:
normalizer = Normalizer()

df_encoded[num_cols_encoded] = normalizer.fit_transform(df_encoded[num_cols_encoded])

In [ ]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["DayOfWeek"] = df["Date"].dt.dayofweek
df["Quarter"] = df["Date"].dt.quarter
df["IsWeekend"] = df["DayOfWeek"].apply(lambda x: 1 if x >= 5 else 0)

In [42]:
df["Revenue"] = df["Unit_Price"] * df["Order_Quantity"]

In [43]:
df["Avg_Order_Value"] = df["Revenue"] / (df["Order_Quantity"] + 1)

In [44]:
df["Price_per_Unit"] = df["Revenue"] / (df["Order_Quantity"] + 1)

In [53]:
fig = px.histogram(df, x="Revenue", nbins=50,
                   title="Revenue Distribution",
                   color_discrete_sequence=["royalblue"])
fig.show()

In [54]:
category_rev = df.groupby("Product_Category")["Revenue"].sum().reset_index()

fig = px.bar(category_rev,
             x="Product_Category",
             y="Revenue",
             title="Total Revenue by Product Category",
             color="Revenue")
fig.show()

In [55]:
year_rev = df.groupby("Year")["Revenue"].sum().reset_index()

fig = px.line(year_rev,
              x="Year",
              y="Revenue",
              markers=True,
              title="Revenue Over Years")
fig.show()

In [56]:
fig = px.scatter(df,
                 x="Revenue",
                 y="Profit",
                 color="Product_Category",
                 title="Profit vs Revenue")
fig.show()