In [60]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [61]:
df = pd.read_csv(r"D:\DEPI R4 ML\Data Sets\WineQT.csv")

In [62]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [64]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

In [65]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

In [66]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [67]:

fig = px.box(
    df,
    x="quality",
    y="alcohol",
    color="quality",
    title="Alcohol Level Distribution by Wine Quality",
    points="all"
)

fig.show()

In [68]:

corr = df.corr()

fig = ff.create_annotated_heatmap(
    z=corr.values,
    x=list(corr.columns),
    y=list(corr.index),
    annotation_text=np.round(corr.values,2),
    colorscale="RdBu"
)

fig.update_layout(title="Correlation Matrix - Wine Dataset")
fig.show()

In [69]:
fig = px.scatter_3d(
    df,
    x="alcohol",
    y="volatile acidity",
    z="sulphates",
    color="quality",
    title="3D Relationship Between Key Chemical Features"
)

fig.show()

In [70]:
important_cols = ["alcohol", "volatile acidity", "sulphates", "density", "quality"]

fig = px.scatter_matrix(
    df,
    dimensions=important_cols,
    color="quality",
    title="Scatter Matrix - Key Chemical Features"
)
fig.show()

In [71]:
df["quality_class"] = df["quality"].apply(lambda x: 1 if x >= 6 else 0)

X = df.drop(["quality", "quality_class"], axis=1)
y = df["quality_class"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

importances = model.feature_importances_

importance_df = pd.DataFrame({
    "Feature": X.columns,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

importance_df

                 Feature  Importance
10               alcohol    0.174656
9              sulphates    0.136240
1       volatile acidity    0.118012
6   total sulfur dioxide    0.086261
7                density    0.080417
11                    Id    0.074291
4              chlorides    0.062762
0          fixed acidity    0.058568
2            citric acid    0.058372
8                     pH    0.055499
5    free sulfur dioxide    0.048757
3         residual sugar    0.046164

In [33]:
df["alcohol_level"] = pd.cut(
    df["alcohol"],
    bins=[0,10,12,15],
    labels=["Low","Medium","High"]
)

هدمج فيتشر مع بعضها عشان مترابطه مع بعض بس مش مهمه في الداتا مع التارجت

In [34]:
df["acid_balance"] = df["fixed acidity"] + df["volatile acidity"] - df["citric acid"]

In [35]:
df["sulfur_ratio"] = df["free sulfur dioxide"] / (df["total sulfur dioxide"] + 1)

In [72]:
df["log_sulfur"] = np.log1p(df["total sulfur dioxide"])

#### Visualization Insights – Wine Quality Dataset

- Observed a clear positive relationship between alcohol level and wine quality.
- Higher quality wines (7–8) tend to have higher median alcohol content.
- Lower quality wines (3–4) generally show lower alcohol levels.
  Alcohol is one of the strongest indicators of wine quality.

- Alcohol shows a positive correlation with quality.
- Volatile acidity shows a negative correlation with quality.
- Density is negatively correlated with alcohol.
- Free sulfur dioxide and total sulfur dioxide are strongly correlated with each other.
- Fixed acidity and citric acid also show positive correlation.
  Some features are strongly related, which suggests potential multicollinearity.
  This motivated feature engineering to combine or transform related variables.

---

- Higher quality wines cluster around:
  - Higher alcohol
  - Lower volatile acidity
  - Higher sulphates
- There is visible overlap between classes, meaning the problem is not perfectly separable.

🔎 Insight:
Wine quality depends on a combination of chemical properties rather than a single feature.

##### Feature Engineering Justification

Based on visualization and correlation analysis, several transformations were applied:

alchol level
Reason:
Alcohol showed strong impact on quality.
Creating categorical bins helps models capture nonlinear patterns.

---

Created:
acid_balance = fixed acidity + volatile acidity - citric acid

Reason:
These features were chemically related.
Combining them helps reduce redundancy and capture overall acidity effect.

--

Created:
sulfur_ratio = free sulfur dioxide / total sulfur dioxide

Reason:
These two features were highly correlated.
Creating a ratio captures sulfur balance more effectively.

Applied log transformation on sulfur-related columns.

Reason:
Some chemical variables were right-skewed.
Log transformation stabilizes variance and improves model performance.